version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
      time: "08:00"
      timezone: "Europe/London"
    target-branch: "master"
    open-pull-requests-limit: 10
    versioning-strategy: increase
    groups:
      all-dependencies:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
