version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
      time: "08:00"
      timezone: "Europe/London"
    target-branch: "master"
    open-pull-requests-limit: 10
    versioning-strategy: increase
    groups:
      all-dependencies:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    ignore:
      - dependency-name: "@types/node"
        versions: [">= 25.0.0"]
      # SOL-18791 Upgrade to ESLint v10
      - dependency-name: "@eslint/js"
        versions: [">= 10.0.0"]
      # SOL-18791 Upgrade to ESLint v10
      - dependency-name: "eslint"
        versions: [">= 10.0.0"]
      # SOL-19173 Upgrade to TypeScript 6.x
      - dependency-name: "typescript"
        versions: [">= 6.0.0"]
